### ISSUE TITLE
Error opening MeshViewer or MultiMeshViewer in macOS

### ISSUE THREAD

**Issue by ricardoavelino** [compas-dev/compas_viewers#1]
**Describe the bug**
Can't visualise the MeshViewer and MultiMeshViewer in Mac.

**To Reproduce**
When running the examples meshviewer/app.py or multimeshviewer/app.py I get the following error message.

> qt.qpa.plugin: Could not load the Qt platform plugin "cocoa" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> Available platform plugins are: cocoa, minimal, offscreen, webgl.
> Abort` trap: 6

The same happens if I import one of the viewers in my own code, I can't open it and get the same error. The VtkViewer opens when I run the example file vtkviewer.py

**Help online**
Trying to debug it myself I found suggestions in [https://forum.qt.io/topic/98816/qt-could-not-find-the-platform-plugin-cocoa/13](url) one of them suggests installing Qt as a separated "software", but I thought that it should be already incorporated in the package PySide2. 

Do you have a suggestion of what I should do to open the viewer?

**My current Set up**
 - Mac
 - Python version 3.6.7
 - OpenGL version 3.1.3b2
 - PySide2 version 5.13.2

Thank you!

**Comment by GeneKao** [comment]
@ricardoavelino. the viewers work on my environment. 

Here are my packages versions. Please try to install them, I hope it helps. 
```
python=3.6.7
pyqt=5.12.3
pyside2=5.13.1
pyopengl=3.1.1a1
qt=5.12.5
qtconsole=4.6.0
tk=8.6.10
```

**Comment by brgcode** [comment]
indeed, perhaps just try to reinstall qt and pyqt as suggested

**Comment by ricardoavelino** [comment]
Indeed, updating all my packages to the newest version and making sure they were installed with conda (conda-forge) instead of pip made it work.

Thank you all.
