### ISSUE TITLE
OpenGL.error.NullFunctionError

### ISSUE THREAD

**Issue by Licini** [compas-dev/compas_viewers#9]
**Describe the bug**
```
Traceback (most recent call last):
  File "d:\github\compas_viewers\src\compas_viewers\core\glwidget.py", line 86, in initializeGL
    glutInitDisplayMode(GLUT_DOUBLE | GLUT_RGB | GLUT_DEPTH)
  File "C:\Users\leoch\Anaconda3\envs\compas-dev\lib\site-packages\OpenGL\platform\baseplatform.py", line 425, in __call__
    self.__name__, self.__name__,
OpenGL.error.NullFunctionError: Attempt to call an undefined function glutInitDisplayMode, check for bool(glutInitDisplayMode) before calling
Traceback (most recent call last):
  File "d:\github\compas_viewers\src\compas_viewers\core\glwidget.py", line 86, in initializeGL
    glutInitDisplayMode(GLUT_DOUBLE | GLUT_RGB | GLUT_DEPTH)
  File "C:\Users\leoch\Anaconda3\envs\compas-dev\lib\site-packages\OpenGL\platform\baseplatform.py", line 425, in __call__
    self.__name__, self.__name__,
OpenGL.error.NullFunctionError: Attempt to call an undefined function glutInitDisplayMode, check for bool(glutInitDisplayMode) before calling
```

**To Reproduce**
`python examples/multimesh.py`

**Expected behavior**
The viewer still able to run after despite the error.

**Desktop (please complete the following information):**
 - OS:  Win10
 - Python version 3.7
 - Python package manager pip installed in an conda env

**Comment by Licini** [comment]
Error seems go away by commenting out `src\compas_viewers\core\glwidget.py` line 86

**Comment by Licini** [comment]
Or can be fixed by downloading corresponding whl manuanlly from
https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyopengl    
Then   
`pip install PyOpenGL-3.1.5-cp37-cp37m-win_amd64.whl`

**Comment by brgcode** [comment]
this is an old one...
https://block.arch.ethz.ch/blog/2016/10/pyopengl-glut-error/

**Comment by brgcode** [comment]
did you install PyOpenGL via conda, because that is supposed to work as well...

**Comment by Licini** [comment]
yep I did with conda and it gave same error with plain `conda install pyopengy`, should I do it through certain channel??

**Comment by brgcode** [comment]
no i guess on windows you have to use the wheel of gohlke
